version: '3.0'
services:
  front-end:
    image: "gitlab-registry.isae-supaero.fr/jsatorb-dev/stage/stage-2021-julien_prissimitzis/luplink-front:dev"
    ports:   
      - "81:80"
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/var/cache/nginx'
      - '/usr/share/nginx/html'
  api:
    image: gitlab-registry.isae-supaero.fr/jsatorb-dev/stage/stage-2021-julien_prissimitzis/luplink-api:dev
    ports:
      - "8001:8001"
    restart: always


