version: '3.2'
services:
  api:
    image: gitlab-registry.isae-supaero.fr/jsatorb-dev/stage/stage-2021-julien_prissimitzis/jsatorb-api:dev
    ports:
      - "8001:8001"
    restart: always
  # JSatOrb's backend container
  backend:
    container_name: jsatorb-backend-luplink-container
    image: jsatorb-backend:prod
    ports:
      - "8000:8000"
    user: "${USER_ID}:${GROUP_UID}"
    volumes:
      - type: "bind"
        source: "/home/${USER}/JSatOrb/mission-data"
        target: "/JSatOrb/mission-data"
    restart: always

  # JSatOrb's frontend container
  front-end:
    container_name: jsatorb-frontend-luplink-container
    depends_on:
        - backend
    image: "gitlab-registry.isae-supaero.fr/jsatorb-dev/stage/stage-2021-julien_prissimitzis/jsatorb-frontend-luplink:prod"
    ports:   
      - "80:80"
    restart: always
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    #   - '/var/cache/nginx'
    #   - '/usr/share/nginx/html'

  # JSatOrb's Celestrak container
  celestrak:
    container_name: celestrak-json-proxy-luplink-container
    image: thib21/celestrak-json-proxy:dev
    ports:
      - "7777:7777"
    restart: always


